name: Social Network CI

on:
  push:
    branches: [ main ]

jobs:
  test_network:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        pip3 install --user django
        pip3 install djangorestframework
        python3 manage.py test
